/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginSlugRouteImport } from './routes/login.$slug'
import { Route as OwnerIndexRouteImport } from './routes/owner.index'
import { Route as OwnerAccessRouteImport } from './routes/owner.access'
import { Route as OwnerComplianceRouteImport } from './routes/owner.compliance'
import { Route as OwnerFinanceRouteImport } from './routes/owner.finance'
import { Route as OwnerStudentsRouteImport } from './routes/owner.students'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as PlatformNewCenterRouteImport } from './routes/platform.new-center'
import { Route as StaffIndexRouteImport } from './routes/staff.index'
import { Route as StaffBookletsRouteImport } from './routes/staff.booklets'
import { Route as StaffCashierRouteImport } from './routes/staff.cashier'
import { Route as StaffShiftRouteImport } from './routes/staff.shift'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentLeaderboardRouteImport } from './routes/student.leaderboard'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherAssessmentsRouteImport } from './routes/teacher.assessments'
import { Route as TeacherCurriculumRouteImport } from './routes/teacher.curriculum'
import { Route as VisitorIndexRouteImport } from './routes/visitor.index'
import { Route as TeacherSessionGroupIdRouteImport } from './routes/teacher.session.$groupId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginSlugRoute = LoginSlugRouteImport.update({
  id: '/login/$slug',
  path: '/login/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerIndexRoute = OwnerIndexRouteImport.update({
  id: '/owner/',
  path: '/owner/',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerAccessRoute = OwnerAccessRouteImport.update({
  id: '/owner/access',
  path: '/owner/access',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerComplianceRoute = OwnerComplianceRouteImport.update({
  id: '/owner/compliance',
  path: '/owner/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerFinanceRoute = OwnerFinanceRouteImport.update({
  id: '/owner/finance',
  path: '/owner/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerStudentsRoute = OwnerStudentsRouteImport.update({
  id: '/owner/students',
  path: '/owner/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/parent/',
  path: '/parent/',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/parent/messages',
  path: '/parent/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformNewCenterRoute = PlatformNewCenterRouteImport.update({
  id: '/platform/new-center',
  path: '/platform/new-center',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffIndexRoute = StaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffBookletsRoute = StaffBookletsRouteImport.update({
  id: '/staff/booklets',
  path: '/staff/booklets',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffCashierRoute = StaffCashierRouteImport.update({
  id: '/staff/cashier',
  path: '/staff/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffShiftRoute = StaffShiftRouteImport.update({
  id: '/staff/shift',
  path: '/staff/shift',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/student/',
  path: '/student/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLeaderboardRoute = StudentLeaderboardRouteImport.update({
  id: '/student/leaderboard',
  path: '/student/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/teacher/',
  path: '/teacher/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherAssessmentsRoute = TeacherAssessmentsRouteImport.update({
  id: '/teacher/assessments',
  path: '/teacher/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherCurriculumRoute = TeacherCurriculumRouteImport.update({
  id: '/teacher/curriculum',
  path: '/teacher/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const VisitorIndexRoute = VisitorIndexRouteImport.update({
  id: '/visitor/',
  path: '/visitor/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherSessionGroupIdRoute = TeacherSessionGroupIdRouteImport.update({
  id: '/teacher/session/$groupId',
  path: '/teacher/session/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login/$slug': typeof LoginSlugRoute
  '/owner/access': typeof OwnerAccessRoute
  '/owner/compliance': typeof OwnerComplianceRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/platform/new-center': typeof PlatformNewCenterRoute
  '/staff/booklets': typeof StaffBookletsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/shift': typeof StaffShiftRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/owner/': typeof OwnerIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/visitor/': typeof VisitorIndexRoute
  '/teacher/session/$groupId': typeof TeacherSessionGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login/$slug': typeof LoginSlugRoute
  '/owner/access': typeof OwnerAccessRoute
  '/owner/compliance': typeof OwnerComplianceRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/platform/new-center': typeof PlatformNewCenterRoute
  '/staff/booklets': typeof StaffBookletsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/shift': typeof StaffShiftRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/owner': typeof OwnerIndexRoute
  '/parent': typeof ParentIndexRoute
  '/staff': typeof StaffIndexRoute
  '/student': typeof StudentIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/visitor': typeof VisitorIndexRoute
  '/teacher/session/$groupId': typeof TeacherSessionGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login/$slug': typeof LoginSlugRoute
  '/owner/access': typeof OwnerAccessRoute
  '/owner/compliance': typeof OwnerComplianceRoute
  '/owner/finance': typeof OwnerFinanceRoute
  '/owner/students': typeof OwnerStudentsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/platform/new-center': typeof PlatformNewCenterRoute
  '/staff/booklets': typeof StaffBookletsRoute
  '/staff/cashier': typeof StaffCashierRoute
  '/staff/shift': typeof StaffShiftRoute
  '/student/leaderboard': typeof StudentLeaderboardRoute
  '/teacher/assessments': typeof TeacherAssessmentsRoute
  '/teacher/curriculum': typeof TeacherCurriculumRoute
  '/owner/': typeof OwnerIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/student/': typeof StudentIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/visitor/': typeof VisitorIndexRoute
  '/teacher/session/$groupId': typeof TeacherSessionGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login/$slug'
    | '/owner/access'
    | '/owner/compliance'
    | '/owner/finance'
    | '/owner/students'
    | '/parent/messages'
    | '/platform/new-center'
    | '/staff/booklets'
    | '/staff/cashier'
    | '/staff/shift'
    | '/student/leaderboard'
    | '/teacher/assessments'
    | '/teacher/curriculum'
    | '/owner/'
    | '/parent/'
    | '/staff/'
    | '/student/'
    | '/teacher/'
    | '/visitor/'
    | '/teacher/session/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login/$slug'
    | '/owner/access'
    | '/owner/compliance'
    | '/owner/finance'
    | '/owner/students'
    | '/parent/messages'
    | '/platform/new-center'
    | '/staff/booklets'
    | '/staff/cashier'
    | '/staff/shift'
    | '/student/leaderboard'
    | '/teacher/assessments'
    | '/teacher/curriculum'
    | '/owner'
    | '/parent'
    | '/staff'
    | '/student'
    | '/teacher'
    | '/visitor'
    | '/teacher/session/$groupId'
  id:
    | '__root__'
    | '/'
    | '/login/$slug'
    | '/owner/access'
    | '/owner/compliance'
    | '/owner/finance'
    | '/owner/students'
    | '/parent/messages'
    | '/platform/new-center'
    | '/staff/booklets'
    | '/staff/cashier'
    | '/staff/shift'
    | '/student/leaderboard'
    | '/teacher/assessments'
    | '/teacher/curriculum'
    | '/owner/'
    | '/parent/'
    | '/staff/'
    | '/student/'
    | '/teacher/'
    | '/visitor/'
    | '/teacher/session/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginSlugRoute: typeof LoginSlugRoute
  OwnerAccessRoute: typeof OwnerAccessRoute
  OwnerComplianceRoute: typeof OwnerComplianceRoute
  OwnerFinanceRoute: typeof OwnerFinanceRoute
  OwnerStudentsRoute: typeof OwnerStudentsRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  PlatformNewCenterRoute: typeof PlatformNewCenterRoute
  StaffBookletsRoute: typeof StaffBookletsRoute
  StaffCashierRoute: typeof StaffCashierRoute
  StaffShiftRoute: typeof StaffShiftRoute
  StudentLeaderboardRoute: typeof StudentLeaderboardRoute
  TeacherAssessmentsRoute: typeof TeacherAssessmentsRoute
  TeacherCurriculumRoute: typeof TeacherCurriculumRoute
  OwnerIndexRoute: typeof OwnerIndexRoute
  ParentIndexRoute: typeof ParentIndexRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StudentIndexRoute: typeof StudentIndexRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
  VisitorIndexRoute: typeof VisitorIndexRoute
  TeacherSessionGroupIdRoute: typeof TeacherSessionGroupIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/$slug': {
      id: '/login/$slug'
      path: '/login/$slug'
      fullPath: '/login/$slug'
      preLoaderRoute: typeof LoginSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/': {
      id: '/owner/'
      path: '/owner'
      fullPath: '/owner/'
      preLoaderRoute: typeof OwnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/access': {
      id: '/owner/access'
      path: '/owner/access'
      fullPath: '/owner/access'
      preLoaderRoute: typeof OwnerAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/compliance': {
      id: '/owner/compliance'
      path: '/owner/compliance'
      fullPath: '/owner/compliance'
      preLoaderRoute: typeof OwnerComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/finance': {
      id: '/owner/finance'
      path: '/owner/finance'
      fullPath: '/owner/finance'
      preLoaderRoute: typeof OwnerFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/students': {
      id: '/owner/students'
      path: '/owner/students'
      fullPath: '/owner/students'
      preLoaderRoute: typeof OwnerStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/parent'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/parent/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/new-center': {
      id: '/platform/new-center'
      path: '/platform/new-center'
      fullPath: '/platform/new-center'
      preLoaderRoute: typeof PlatformNewCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/staff'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/booklets': {
      id: '/staff/booklets'
      path: '/staff/booklets'
      fullPath: '/staff/booklets'
      preLoaderRoute: typeof StaffBookletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/cashier': {
      id: '/staff/cashier'
      path: '/staff/cashier'
      fullPath: '/staff/cashier'
      preLoaderRoute: typeof StaffCashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff/shift': {
      id: '/staff/shift'
      path: '/staff/shift'
      fullPath: '/staff/shift'
      preLoaderRoute: typeof StaffShiftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/student'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/leaderboard': {
      id: '/student/leaderboard'
      path: '/student/leaderboard'
      fullPath: '/student/leaderboard'
      preLoaderRoute: typeof StudentLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/teacher'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/assessments': {
      id: '/teacher/assessments'
      path: '/teacher/assessments'
      fullPath: '/teacher/assessments'
      preLoaderRoute: typeof TeacherAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/curriculum': {
      id: '/teacher/curriculum'
      path: '/teacher/curriculum'
      fullPath: '/teacher/curriculum'
      preLoaderRoute: typeof TeacherCurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visitor/': {
      id: '/visitor/'
      path: '/visitor'
      fullPath: '/visitor/'
      preLoaderRoute: typeof VisitorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/session/$groupId': {
      id: '/teacher/session/$groupId'
      path: '/teacher/session/$groupId'
      fullPath: '/teacher/session/$groupId'
      preLoaderRoute: typeof TeacherSessionGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginSlugRoute: LoginSlugRoute,
  OwnerAccessRoute: OwnerAccessRoute,
  OwnerComplianceRoute: OwnerComplianceRoute,
  OwnerFinanceRoute: OwnerFinanceRoute,
  OwnerStudentsRoute: OwnerStudentsRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  PlatformNewCenterRoute: PlatformNewCenterRoute,
  StaffBookletsRoute: StaffBookletsRoute,
  StaffCashierRoute: StaffCashierRoute,
  StaffShiftRoute: StaffShiftRoute,
  StudentLeaderboardRoute: StudentLeaderboardRoute,
  TeacherAssessmentsRoute: TeacherAssessmentsRoute,
  TeacherCurriculumRoute: TeacherCurriculumRoute,
  OwnerIndexRoute: OwnerIndexRoute,
  ParentIndexRoute: ParentIndexRoute,
  StaffIndexRoute: StaffIndexRoute,
  StudentIndexRoute: StudentIndexRoute,
  TeacherIndexRoute: TeacherIndexRoute,
  VisitorIndexRoute: VisitorIndexRoute,
  TeacherSessionGroupIdRoute: TeacherSessionGroupIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
