-- SUPABASE_MIGRATION_SPEC.md §1 — curriculum plan + AI-generated lesson content
-- (TEACHER_MODULE_SPEC.md §4-b / CURRICULUM_ENGINE_SPEC.md §8, §13).

create table if not exists lessons (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  group_id text not null references groups (id) on delete cascade,
  subject_id text not null references subjects (id) on delete restrict,
  title text not null,
  source_file_name text,
  extracted_text text,
  content_hash text,
  ai_status text not null check (ai_status in ('idle', 'processing', 'ready', 'failed')),
  ai_error text,
  taught_status text not null check (taught_status in ('not_started', 'in_progress', 'done')),
  taught_at timestamptz,
  actual_duration_seconds integer,
  created_by_teacher_id text not null references teachers (id) on delete restrict
);
create index if not exists idx_lessons_center_id on lessons (center_id);
create index if not exists idx_lessons_group_id on lessons (group_id);
create index if not exists idx_lessons_content_hash on lessons (content_hash);

-- Pre-Phase-2 static slide deck / question bank rows have lesson_id null in the app's own
-- type comments — kept nullable here too, but every *row* still carries a real center_id
-- (this app's seed has no shared cross-tenant demo content; each new client onboarded via
-- §8 starts empty, so there's no reason for these to ever be tenant-less).
create table if not exists lesson_slides (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  lesson_id text references lessons (id) on delete cascade,
  "index" integer not null,
  title text not null,
  bullets text[] not null default '{}'
);
create index if not exists idx_lesson_slides_center_id on lesson_slides (center_id);
create index if not exists idx_lesson_slides_lesson_id on lesson_slides (lesson_id);

-- CURRICULUM_ENGINE_SPEC.md §8 — question variety (mcq/true_false/ordering/matching).
-- `QuizQuestion` is reused verbatim for the in-session random picker AND embedded inside
-- electronic_homeworks.questions (jsonb there, see below) — this table is the picker's bank.
create table if not exists session_questions (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  lesson_id text references lessons (id) on delete cascade,
  source text not null check (source in ('ai_generated', 'manual')),
  kind text not null check (kind in ('mcq', 'true_false', 'ordering', 'matching')),
  text text not null,
  options text[] not null default '{}',
  correct_index integer not null default 0,
  match_targets text[]
);
create index if not exists idx_session_questions_center_id on session_questions (center_id);
create index if not exists idx_session_questions_lesson_id on session_questions (lesson_id);

create table if not exists curriculum_units (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  subject_id text not null references subjects (id) on delete restrict,
  grade_id text not null references grades (id) on delete restrict,
  name text not null,
  "order" integer not null,
  planned_duration_days integer not null default 0
);
create index if not exists idx_curriculum_units_center_id on curriculum_units (center_id);
create index if not exists idx_curriculum_units_subject_id on curriculum_units (subject_id);
create index if not exists idx_curriculum_units_grade_id on curriculum_units (grade_id);

-- No center_id on `CurriculumLesson` in the TS type either — denormalized here too, same
-- reasoning as grade_subjects above.
create table if not exists curriculum_lessons (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  unit_id text not null references curriculum_units (id) on delete cascade,
  "order" integer not null,
  title text not null,
  status text not null check (status in ('not_started', 'in_progress', 'done')),
  linked_lesson_id text references lessons (id) on delete set null
);
create index if not exists idx_curriculum_lessons_center_id on curriculum_lessons (center_id);
create index if not exists idx_curriculum_lessons_unit_id on curriculum_lessons (unit_id);

-- §8 — one suggested activity per lesson, generated by the stub pipeline.
create table if not exists suggested_activities (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  lesson_id text not null references lessons (id) on delete cascade,
  type text not null check (type in ('visit', 'draw', 'observe', 'practice', 'other')),
  title text not null,
  description text not null
);
create index if not exists idx_suggested_activities_center_id on suggested_activities (center_id);
create index if not exists idx_suggested_activities_lesson_id on suggested_activities (lesson_id);

-- `questions` is stored as jsonb (embedding QuizQuestion[] verbatim), matching the TS
-- interface exactly (`ElectronicHomework.questions: QuizQuestion[]` is an embedded array,
-- not a join relation in the app's own model) rather than inventing a new normalized shape.
create table if not exists electronic_homeworks (
  id text primary key,
  center_id text not null references centers (id) on delete cascade,
  lesson_id text not null references lessons (id) on delete cascade,
  group_id text not null references groups (id) on delete cascade,
  questions jsonb not null default '[]',
  due_at text not null
);
create index if not exists idx_electronic_homeworks_center_id on electronic_homeworks (center_id);
create index if not exists idx_electronic_homeworks_lesson_id on electronic_homeworks (lesson_id);
create index if not exists idx_electronic_homeworks_group_id on electronic_homeworks (group_id);
